-- Teste no banco com perfis temporários e claims simuladas; nada é persistido.
-- Execute com conexão administrativa. Todos os comandos de teste usam role authenticated/anon.
begin;
create temp table qa_result(label text,passed boolean,detail text);
grant all on qa_result to authenticated,anon;
create function pg_temp.qa_check(label text, statement text, expected bigint default 0, denied boolean default false) returns void language plpgsql security invoker as $test$
declare n bigint;
begin
  begin
    execute statement into n;
    insert into qa_result values(label, not denied and n=expected, 'rows='||coalesce(n::text,'null'));
  exception when others then
    insert into qa_result values(label, denied and SQLSTATE in ('42501','23503','23514'), SQLSTATE||': '||SQLERRM);
  end;
end $test$;
insert into public."dEmpresas"("ID_Empresa","Nome_Empresa") values ('QA_SEC_A','QA segurança A'),('QA_SEC_B','QA segurança B');
insert into auth.users(id,email,aud,role) values ('02102026-0000-4000-8000-000000000001','qa-security-1@example.invalid','authenticated','authenticated'),('02102026-0000-4000-8000-000000000002','qa-security-2@example.invalid','authenticated','authenticated'),('02102026-0000-4000-8000-000000000003','qa-security-3@example.invalid','authenticated','authenticated'),('02102026-0000-4000-8000-000000000004','qa-security-4@example.invalid','authenticated','authenticated'),('02102026-0000-4000-8000-000000000005','qa-security-5@example.invalid','authenticated','authenticated');
insert into public."dUsuarios"("ID_Usuario","Nome","ID_Empresa","Perfil","Status") values ('02102026-0000-4000-8000-000000000001','QA segurança owner','QA_SEC_A','owner','Ativo'),('02102026-0000-4000-8000-000000000002','QA segurança admin','QA_SEC_A','admin','Ativo'),('02102026-0000-4000-8000-000000000003','QA segurança operacional','QA_SEC_A','operacional','Ativo'),('02102026-0000-4000-8000-000000000004','QA segurança admin','QA_SEC_B','admin','Ativo'),('02102026-0000-4000-8000-000000000005','QA segurança operacional','QA_SEC_A','operacional','Inativo');
insert into public."dClientes"("ID_Cliente","ID_Empresa","Nome_Cliente") values('QA_SEC_C_A','QA_SEC_A','QA cliente');
insert into public."dObras"("ID_Obra","ID_Empresa","ID_Cliente","Nome_Obra") values('QA_SEC_O_A','QA_SEC_A','QA_SEC_C_A','QA obra');
insert into public."dTrabalhadores"("ID_Trabalhador","ID_Empresa","Nome_Trabalhador") values('QA_SEC_T_A','QA_SEC_A','QA trabalhador');
insert into public."dCategoriaGastos"("ID_Categoria","ID_Empresa","Nome_Categoria") values('QA_SEC_K_A','QA_SEC_A','QA categoria');
insert into public."fRecebimentosObras"("ID_Recebimento","ID_Empresa","ID_Obra","Valor_Recebido","Data_Recebimento","Criado_Por") values('QA_SEC_R_A','QA_SEC_A','QA_SEC_O_A',10,current_date,'02102026-0000-4000-8000-000000000002');
insert into public."fSaidasObras"("ID_Saida","ID_Empresa","ID_Obra","ID_Categoria","Valor","Data_Saida","Criado_Por") values('QA_SEC_S_A','QA_SEC_A','QA_SEC_O_A','QA_SEC_K_A',5,current_date,'02102026-0000-4000-8000-000000000002');
insert into public."fPagamentosMaoDeObra"("ID_Pagamento","ID_Empresa","ID_Obra","ID_Trabalhador","Valor_Pago","Data_Pagamento","Criado_Por") values('QA_SEC_P_A','QA_SEC_A','QA_SEC_O_A','QA_SEC_T_A',2,current_date,'02102026-0000-4000-8000-000000000002');
insert into public."dClientes"("ID_Cliente","ID_Empresa","Nome_Cliente") values('QA_SEC_C_B','QA_SEC_B','QA cliente');
insert into public."dObras"("ID_Obra","ID_Empresa","ID_Cliente","Nome_Obra") values('QA_SEC_O_B','QA_SEC_B','QA_SEC_C_B','QA obra');
insert into public."dTrabalhadores"("ID_Trabalhador","ID_Empresa","Nome_Trabalhador") values('QA_SEC_T_B','QA_SEC_B','QA trabalhador');
insert into public."dCategoriaGastos"("ID_Categoria","ID_Empresa","Nome_Categoria") values('QA_SEC_K_B','QA_SEC_B','QA categoria');
insert into public."fRecebimentosObras"("ID_Recebimento","ID_Empresa","ID_Obra","Valor_Recebido","Data_Recebimento","Criado_Por") values('QA_SEC_R_B','QA_SEC_B','QA_SEC_O_B',10,current_date,'02102026-0000-4000-8000-000000000002');
insert into public."fSaidasObras"("ID_Saida","ID_Empresa","ID_Obra","ID_Categoria","Valor","Data_Saida","Criado_Por") values('QA_SEC_S_B','QA_SEC_B','QA_SEC_O_B','QA_SEC_K_B',5,current_date,'02102026-0000-4000-8000-000000000002');
insert into public."fPagamentosMaoDeObra"("ID_Pagamento","ID_Empresa","ID_Obra","ID_Trabalhador","Valor_Pago","Data_Pagamento","Criado_Por") values('QA_SEC_P_B','QA_SEC_B','QA_SEC_O_B','QA_SEC_T_B',2,current_date,'02102026-0000-4000-8000-000000000002');
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('1-owner-Ativo leitura propria dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa dEmpresas',$qa$with m as(update public."dEmpresas" set "Nome_Empresa"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa dEmpresas',$qa$with m as(delete from public."dEmpresas" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa dClientes',$qa$with m as(delete from public."dClientes" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa dObras',$qa$with m as(delete from public."dObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa dTrabalhadores',$qa$with m as(delete from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa dCategoriaGastos',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa fRecebimentosObras',$qa$with m as(delete from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa fSaidasObras',$qa$with m as(delete from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura propria fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo leitura outra empresa fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update outra empresa fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo delete outra empresa fPagamentosMaoDeObra',$qa$with m as(delete from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo update proprio fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('1-owner-Ativo view outra empresa vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo view outra empresa vw_fluxo_mensal',$qa$select count(*) from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo usuarios outra empresa',$qa$select count(*) from public."dUsuarios" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('1-owner-Ativo insert outra empresa cliente',$qa$with m as(insert into public."dClientes"("ID_Cliente","ID_Empresa") values('QA_SEC_INSERT_0','QA_SEC_B') returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('1-owner-Ativo transferir cliente outra empresa',$qa$with m as(update public."dClientes" set "ID_Empresa"='QA_SEC_B' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('1-owner-Ativo excluir categoria propria',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,true);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000002","role":"authenticated","aal":"aal1","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('2-admin-Ativo leitura propria dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa dEmpresas',$qa$with m as(update public."dEmpresas" set "Nome_Empresa"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa dEmpresas',$qa$with m as(delete from public."dEmpresas" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa dClientes',$qa$with m as(delete from public."dClientes" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa dObras',$qa$with m as(delete from public."dObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa dTrabalhadores',$qa$with m as(delete from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa dCategoriaGastos',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa fRecebimentosObras',$qa$with m as(delete from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa fSaidasObras',$qa$with m as(delete from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura propria fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo leitura outra empresa fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update outra empresa fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo delete outra empresa fPagamentosMaoDeObra',$qa$with m as(delete from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo update proprio fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('2-admin-Ativo view outra empresa vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo view outra empresa vw_fluxo_mensal',$qa$select count(*) from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo usuarios outra empresa',$qa$select count(*) from public."dUsuarios" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo escalada de perfil',$qa$with m as(update public."dUsuarios" set "Perfil"='owner' where "ID_Usuario"='02102026-0000-4000-8000-000000000002' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('2-admin-Ativo insert outra empresa cliente',$qa$with m as(insert into public."dClientes"("ID_Cliente","ID_Empresa") values('QA_SEC_INSERT_1','QA_SEC_B') returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('2-admin-Ativo transferir cliente outra empresa',$qa$with m as(update public."dClientes" set "ID_Empresa"='QA_SEC_B' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('2-admin-Ativo excluir categoria propria',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000003","role":"authenticated","aal":"aal1","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('3-operacional-Ativo leitura propria dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa dEmpresas',$qa$with m as(update public."dEmpresas" set "Nome_Empresa"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa dEmpresas',$qa$with m as(delete from public."dEmpresas" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa dClientes',$qa$with m as(delete from public."dClientes" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa dObras',$qa$with m as(delete from public."dObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa dTrabalhadores',$qa$with m as(delete from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa dCategoriaGastos',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa fRecebimentosObras',$qa$with m as(delete from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa fSaidasObras',$qa$with m as(delete from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo leitura propria fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
select pg_temp.qa_check('3-operacional-Ativo leitura outra empresa fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update outra empresa fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo delete outra empresa fPagamentosMaoDeObra',$qa$with m as(delete from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo update proprio fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo view outra empresa vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo view outra empresa vw_fluxo_mensal',$qa$select count(*) from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo usuarios outra empresa',$qa$select count(*) from public."dUsuarios" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo escalada de perfil',$qa$with m as(update public."dUsuarios" set "Perfil"='owner' where "ID_Usuario"='02102026-0000-4000-8000-000000000003' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('3-operacional-Ativo insert outra empresa cliente',$qa$with m as(insert into public."dClientes"("ID_Cliente","ID_Empresa") values('QA_SEC_INSERT_2','QA_SEC_B') returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('3-operacional-Ativo transferir cliente outra empresa',$qa$with m as(update public."dClientes" set "ID_Empresa"='QA_SEC_B' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('3-operacional-Ativo excluir categoria propria',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000004","role":"authenticated","aal":"aal1","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('4-admin-Ativo leitura propria dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa dEmpresas',$qa$with m as(update public."dEmpresas" set "Nome_Empresa"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa dEmpresas',$qa$with m as(delete from public."dEmpresas" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa dClientes',$qa$with m as(delete from public."dClientes" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa dObras',$qa$with m as(delete from public."dObras" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa dTrabalhadores',$qa$with m as(delete from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa dCategoriaGastos',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa fRecebimentosObras',$qa$with m as(delete from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa fSaidasObras',$qa$with m as(delete from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura propria fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B'$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo leitura outra empresa fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update outra empresa fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo delete outra empresa fPagamentosMaoDeObra',$qa$with m as(delete from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo update proprio fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('4-admin-Ativo view outra empresa vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo view outra empresa vw_fluxo_mensal',$qa$select count(*) from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo usuarios outra empresa',$qa$select count(*) from public."dUsuarios" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo escalada de perfil',$qa$with m as(update public."dUsuarios" set "Perfil"='owner' where "ID_Usuario"='02102026-0000-4000-8000-000000000004' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('4-admin-Ativo insert outra empresa cliente',$qa$with m as(insert into public."dClientes"("ID_Cliente","ID_Empresa") values('QA_SEC_INSERT_3','QA_SEC_A') returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('4-admin-Ativo transferir cliente outra empresa',$qa$with m as(update public."dClientes" set "ID_Empresa"='QA_SEC_A' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('4-admin-Ativo excluir categoria propria',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000005","role":"authenticated","aal":"aal1","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('5-operacional-Inativo leitura propria dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa dEmpresas',$qa$with m as(update public."dEmpresas" set "Nome_Empresa"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa dEmpresas',$qa$with m as(delete from public."dEmpresas" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa dClientes',$qa$with m as(delete from public."dClientes" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio dClientes',$qa$with m as(update public."dClientes" set "Nome_Cliente"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa dObras',$qa$with m as(delete from public."dObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio dObras',$qa$with m as(update public."dObras" set "Nome_Obra"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa dTrabalhadores',$qa$with m as(delete from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio dTrabalhadores',$qa$with m as(update public."dTrabalhadores" set "Nome_Trabalhador"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa dCategoriaGastos',$qa$with m as(delete from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio dCategoriaGastos',$qa$with m as(update public."dCategoriaGastos" set "Nome_Categoria"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa fRecebimentosObras',$qa$with m as(delete from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa fSaidasObras',$qa$with m as(delete from public."fSaidasObras" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura propria fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo leitura outra empresa fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update outra empresa fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA tentativa' where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo delete outra empresa fPagamentosMaoDeObra',$qa$with m as(delete from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_B' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo update proprio fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA atualizado' where "ID_Empresa"='QA_SEC_A' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo view outra empresa vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo view outra empresa vw_fluxo_mensal',$qa$select count(*) from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo usuarios outra empresa',$qa$select count(*) from public."dUsuarios" where "ID_Empresa"='QA_SEC_B'$qa$,0,false);
select pg_temp.qa_check('5-operacional-Inativo escalada de perfil',$qa$with m as(update public."dUsuarios" set "Perfil"='owner' where "ID_Usuario"='02102026-0000-4000-8000-000000000005' returning 1) select count(*) from m$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000003","role":"authenticated","aal":"aal1","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('operacional criar fRecebimentosObras',$qa$with m as(insert into public."fRecebimentosObras"("ID_Recebimento","ID_Empresa","ID_Obra","Observacao") values('QA_SEC_OWN_ID_Recebimento','QA_SEC_A','QA_SEC_O_A','QA proprio') returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('operacional editar proprio fRecebimentosObras',$qa$with m as(update public."fRecebimentosObras" set "Observacao"='QA editado' where "ID_Recebimento"='QA_SEC_OWN_ID_Recebimento' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('operacional excluir proprio fRecebimentosObras',$qa$with m as(delete from public."fRecebimentosObras" where "ID_Recebimento"='QA_SEC_OWN_ID_Recebimento' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('operacional criar fSaidasObras',$qa$with m as(insert into public."fSaidasObras"("ID_Saida","ID_Empresa","ID_Obra","ID_Categoria","Descricao") values('QA_SEC_OWN_ID_Saida','QA_SEC_A','QA_SEC_O_A','QA_SEC_K_A','QA proprio') returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('operacional editar proprio fSaidasObras',$qa$with m as(update public."fSaidasObras" set "Descricao"='QA editado' where "ID_Saida"='QA_SEC_OWN_ID_Saida' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('operacional excluir proprio fSaidasObras',$qa$with m as(delete from public."fSaidasObras" where "ID_Saida"='QA_SEC_OWN_ID_Saida' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('operacional criar fPagamentosMaoDeObra',$qa$with m as(insert into public."fPagamentosMaoDeObra"("ID_Pagamento","ID_Empresa","ID_Obra","ID_Trabalhador","Observacao") values('QA_SEC_OWN_ID_Pagamento','QA_SEC_A','QA_SEC_O_A','QA_SEC_T_A','QA proprio') returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('operacional editar proprio fPagamentosMaoDeObra',$qa$with m as(update public."fPagamentosMaoDeObra" set "Observacao"='QA editado' where "ID_Pagamento"='QA_SEC_OWN_ID_Pagamento' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('operacional excluir proprio fPagamentosMaoDeObra',$qa$with m as(delete from public."fPagamentosMaoDeObra" where "ID_Pagamento"='QA_SEC_OWN_ID_Pagamento' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('operacional criar categoria bloqueado',$qa$with m as(insert into public."dCategoriaGastos"("ID_Categoria","ID_Empresa") values('QA_SEC_CAT_DENY','QA_SEC_A') returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('vinculo cliente de outra empresa bloqueado',$qa$with m as(insert into public."dObras"("ID_Obra","ID_Empresa","ID_Cliente") values('QA_SEC_CROSS_OBRA','QA_SEC_A','QA_SEC_C_B') returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('vinculo obra de outra empresa bloqueado',$qa$with m as(insert into public."fRecebimentosObras"("ID_Recebimento","ID_Empresa","ID_Obra") values('QA_SEC_CROSS_REC','QA_SEC_A','QA_SEC_O_B') returning 1) select count(*) from m$qa$,0,true);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('owner sem MFA dEmpresas',$qa$select count(*) from public."dEmpresas" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA dClientes',$qa$select count(*) from public."dClientes" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA dObras',$qa$select count(*) from public."dObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA dTrabalhadores',$qa$select count(*) from public."dTrabalhadores" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA fSaidasObras',$qa$select count(*) from public."fSaidasObras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
select pg_temp.qa_check('owner sem MFA fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2","user_metadata":{"perfil":"owner","ID_Empresa":"QA_SEC_B"}}',true); set local role authenticated;
select pg_temp.qa_check('owner nao excluir a propria conta',$qa$with m as(delete from public."dUsuarios" where "ID_Usuario"='02102026-0000-4000-8000-000000000001' returning 1) select count(*) from m$qa$,0,false);
select pg_temp.qa_check('owner cria cliente descartavel',$qa$with m as(insert into public."dClientes"("ID_Cliente","ID_Empresa") values('QA_SEC_DELETE_ME','QA_SEC_A') returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('owner exclui cliente sem vinculo',$qa$with m as(delete from public."dClientes" where "ID_Cliente"='QA_SEC_DELETE_ME' returning 1) select count(*) from m$qa$,1,false);
select pg_temp.qa_check('owner exclui perfil temporario',$qa$with m as(delete from public."dUsuarios" where "ID_Usuario"='02102026-0000-4000-8000-000000000005' returning 1) select count(*) from m$qa$,1,false);
reset role; set local role anon;
select pg_temp.qa_check('anon sem acesso dEmpresas',$qa$select count(*) from public."dEmpresas"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso dClientes',$qa$select count(*) from public."dClientes"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso dObras',$qa$select count(*) from public."dObras"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso dTrabalhadores',$qa$select count(*) from public."dTrabalhadores"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso dCategoriaGastos',$qa$select count(*) from public."dCategoriaGastos"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso fRecebimentosObras',$qa$select count(*) from public."fRecebimentosObras"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso fSaidasObras',$qa$select count(*) from public."fSaidasObras"$qa$,0,true);
select pg_temp.qa_check('anon sem acesso fPagamentosMaoDeObra',$qa$select count(*) from public."fPagamentosMaoDeObra"$qa$,0,true);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000003","role":"authenticated","aal":"aal1"}',true); set local role authenticated;
select pg_temp.qa_check('bloquear vinculo externo fSaidasObras.ID_Obra',$qa$with m as(update public."fSaidasObras" set "ID_Obra"='QA_SEC_O_B' where "ID_Saida"='QA_SEC_OWN_ID_Saida' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('bloquear vinculo externo fSaidasObras.ID_Categoria',$qa$with m as(update public."fSaidasObras" set "ID_Categoria"='QA_SEC_K_B' where "ID_Saida"='QA_SEC_OWN_ID_Saida' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('bloquear vinculo externo fPagamentosMaoDeObra.ID_Obra',$qa$with m as(update public."fPagamentosMaoDeObra" set "ID_Obra"='QA_SEC_O_B' where "ID_Pagamento"='QA_SEC_OWN_ID_Pagamento' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('bloquear vinculo externo fPagamentosMaoDeObra.ID_Trabalhador',$qa$with m as(update public."fPagamentosMaoDeObra" set "ID_Trabalhador"='QA_SEC_T_B' where "ID_Pagamento"='QA_SEC_OWN_ID_Pagamento' returning 1) select count(*) from m$qa$,0,true);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2"}',true); set local role authenticated;
select pg_temp.qa_check('bloquear exclusao com dependencias dClientes',$qa$with m as(delete from public."dClientes" where "ID_Cliente"='QA_SEC_C_A' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('bloquear exclusao com dependencias dObras',$qa$with m as(delete from public."dObras" where "ID_Obra"='QA_SEC_O_A' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('bloquear exclusao com dependencias dTrabalhadores',$qa$with m as(delete from public."dTrabalhadores" where "ID_Trabalhador"='QA_SEC_T_A' returning 1) select count(*) from m$qa$,0,true);
select pg_temp.qa_check('view propria positiva vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}',true); set local role authenticated;
select pg_temp.qa_check('view propria sem MFA vw_resumo_obras',$qa$select count(*) from public."vw_resumo_obras" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2"}',true); set local role authenticated;
select pg_temp.qa_check('view propria positiva vw_fluxo_mensal',$qa$select count(distinct "ID_Empresa") from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_A'$qa$,1,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}',true); set local role authenticated;
select pg_temp.qa_check('view propria sem MFA vw_fluxo_mensal',$qa$select count(*) from public."vw_fluxo_mensal" where "ID_Empresa"='QA_SEC_A'$qa$,0,false);
reset role; select set_config('request.jwt.claims','{"sub":"02102026-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2"}',true); set local role authenticated;
reset role;
select count(*) as total, count(*) filter(where passed) as passed,jsonb_agg(jsonb_build_object('test',label,'detail',detail)) filter(where not passed) as failures from qa_result;
do $assert$ begin
  if exists (select 1 from qa_result where not passed) then
    raise exception 'Falha nos testes de isolamento e permissões: confira qa_result.';
  end if;
end $assert$;
rollback;
